AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - db/schema.rb
    - Guardfile

Style/Documentation:
  Enabled: false

Rails/ActionFilter:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/TrailingBlankLines:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/IndentArray:
  EnforcedStyle: consistent

Rails/HasAndBelongsToMany:
  Enabled: false
